#
# Defines environment variables.
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# $HOME/.dotfiles/secrets/zshenv
#
if [[ -f "$HOME/.dotfiles/secrets/zshenv" ]]; then
  source "$HOME/.dotfiles/secrets/zshenv"
fi

#
# $HOME/.dotfiles/zsh/zsh_environment.sh
#
if [[ -f "$HOME/.dotfiles/zsh/zsh_environment.sh" ]]; then
  source "$HOME/.dotfiles/zsh/zsh_environment.sh"
fi

